### ISSUE TITLE
ImportError: DLL load failed while importing pyopenpose

### ISSUE THREAD

**Issue by sayoko17** [gembancud/Cheating-Detection#4]
(testp) C:\Users\79124\testp\Cheating-Detection-master>python runWebVidgear.py
Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?
Traceback (most recent call last):
  File "runWebVidgear.py", line 21, in <module>
    from CheatDetection import CheatDetection
  File "C:\Users\79124\testp\Cheating-Detection-master\CheatDetection\__init__.py", line 49, in <module>
    raise e
  File "C:\Users\79124\testp\Cheating-Detection-master\CheatDetection\__init__.py", line 40, in <module>
    import pyopenpose as op
ImportError: DLL load failed while importing pyopenpose

please tell me what should i do

**Comment by gembancud** [comment]
If you are executing this in windows, I have prebuilt the OpenPose and uploaded them [here](https://drive.google.com/file/d/1OmsF-PqlyDessAruHpESvOnC89eAl4Vz/view)

Although I haven't fully tested them on other systems, so if you cant get it to work then its generally recommended that you build OpenPose for yourself for your system as guided [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation/0_index.md#compiling-and-running-openpose-from-source). Once you build it, you can hopefully place it in the `CheatingDetection` directory to make the scripts run.

Additionally, `runWebVidgear.py` and `runNanoVidgear.py` are co-dependent scripts that have to run simultaneously.

I hope you can make it work on your end. I'll change up the code and documentation to make it more reproducible soon

This image should ideally show how the CheatingDirectory is supposed to look like
